title: Riyaad Azad
email: azad.riyaad@gmail.com

call-to-action: schedule a free consultation
about-button: see my work
pricing-button: view pricing

copyright: Copyright &copy; 2020 Riyaad Azad. All rights reserved.

plugins: 
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
